export const BRAND_EN = "Rice n' Rooster"
export const BRAND_SUBTITLE = "Rice n' Rooster"
export const BRAND_OWNER_NAME = 'Sankaranarayanan. S'
export const BRAND_LOGO = '/logo.png'

export const BRAND_PRIMARY_PHONE_DISPLAY = '+91 93634 00210'
export const BRAND_PRIMARY_PHONE_E164 = '919363400210'
export const BRAND_SECONDARY_PHONE_DISPLAY = '+91 99942 00210'
export const BRAND_SECONDARY_PHONE_E164 = '919994200210'
export const BRAND_THIRD_PHONE_DISPLAY = BRAND_PRIMARY_PHONE_DISPLAY
export const BRAND_THIRD_PHONE_E164 = BRAND_PRIMARY_PHONE_E164
export const BRAND_PHONE_DISPLAY = BRAND_PRIMARY_PHONE_DISPLAY
export const BRAND_PHONE_E164 = BRAND_PRIMARY_PHONE_E164
export const BRAND_WHATSAPP = BRAND_THIRD_PHONE_DISPLAY
export const WHATSAPP_NUM = BRAND_THIRD_PHONE_E164
export const BRAND_WHATSAPP_LINK = `https://wa.me/${BRAND_THIRD_PHONE_E164}`
export const BRAND_EMAIL = 'ricenrooster@gmail.com'
export const BRAND_ADDRESS = '1st floor, 14/A, Water Tank Rd, MMDA Colony, Arumbakkam, Chennai, Tamil Nadu 600106'
export const BRAND_LOCATION_LINK = '#'
export const BRAND_INSTAGRAM = 'ricenrooster'
export const BRAND_INSTAGRAM_LINK = 'https://www.instagram.com/ricenrooster'
